### PR TITLE
Redis options as connect

### PR DESCRIPTION
**Pull request by livertonli12**
Simon,

I tried using the default configuration with Azure Redis Cache and I identified that without passing some aditional arguments to redis, straw couldn't work.

I would appreciate if you accept my PR because i'm using your project into a big solution in my company.

Regards,
Líverton Oliveira.

### CODE REVIEW

**Comment by simonswain** [comment]
Awesome. Thanks for the PR.

**Comment by simonswain** [comment]
Would love to know some details on how you're using Straw.

**Comment by livertonli12** [comment]
Simon,
We are building a solution like stamplay, zapier, ifttt ... to connect softwares that people could save time if they had a solution like ours.Straw helps us a lot because we designed a topology to resolve our integrations. This topology still gets weekly updates as we discover new possibilities of integrations.
Do you know if after merging my pull request, npm will recognize it and serve latest version ?
Regards,
Líverton Oliveira. 

Date: Sat, 23 Jul 2016 17:44:57 -0700

**Comment by simonswain** [comment]
Looks like something in the tests is broken. I'm investigating. 

I will also upgrade it to use a more recent version of Node (>=5.11) will this cause you any issues?

**Comment by livertonli12** [comment]
I tested "grunt test" here and it's all working .I think that node upgrade won't be a problem, we also use >= 5
Regards,Líverton Oliveira.Date: Sat, 23 Jul 2016 19:48:43 -0700

**Comment by simonswain** [comment]
Looks like passing through the opts to Redis also passes `prefix` which I think node-redis has started using. I've tweaked it to only send through the host and port. Can you please have a play with #aa27c6c (make sure you update modules too) and I'll push this out as v0.4.0 on NPM. Thanks!

**Comment by livertonli12** [comment]
It seems that I can only connect if send a password . Is it okay to merge another lines of code ? I tested here and password is optional but for Azure i really need this.

**Pull request merged**
